### ISSUE TITLE
Add early SIP dialog state

### ISSUE THREAD

**Issue by denyspozniak** [livekit/sip#102]
Hello!
At the moment, when receiving a call, the Livekit SIP gateway answers immediately and only after 4-5 seconds the media stream is switched on. 
Is it possible to enable the progress state (183/SDP) so that the customer can hear the ringing until the media stream is generated?

**Comment by dennwc** [comment]
Hey @denyspozniak!

The latest LK should generate status 180, which resulted in the tone until the media is enabled in my testing.

I will check the spec regarding status 183, don't remember the semantics of it.

**Comment by jamesmcarthur115555** [comment]
Also having this issue , the silence is causing users to hangup as it seems no one has locked up the call
