### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by tricksterANDthug** [livekit/sip#168]
when i perform mage build, the error is below:
kg/media/resample_beep.go:45:9: cannot use r (variable of type *resampleWriter) as WriteCloser[PCM16Sample] value in return statement: *resampleWriter does not implement WriteCloser[PCM16Sample] (missing method String)

**Comment by dennwc** [comment]
You're likely building with CGO disabled. Try setting `CGO_ENABLED=1` explicitly.

**Comment by tricksterANDthug** [comment]
Thank you very much! My LiveKit-SIP installation issue is resolved. You are an amazing engineer and helped solve a problem that had been troubling me for two days
