### ISSUE TITLE
Twilio Test Error

### ISSUE THREAD

**Issue by tricksterANDthug** [livekit/sip#170]
My twilio phone number is +14707983338 and public ip of aws is 107.20.81.14 .I am using Twilio's SIP Trunking service and have deployed the corresponding SIP service on an AWS server with port 5060. The result is show below:
<img width="1292" alt="截屏2024-09-10 17 17 30" src="https://github.com/user-attachments/assets/00ad42dd-8916-43e3-a524-a98989352866">
I have configured the Origination SIP URI in Twilio's SIP Trunking settings as sip:107.20.81.147:5060, where 107.20.81.147 is the server's public IP. Since I am only using the inbound functionality, no configuration was made in the Termination URI. The ports 5060 and the corresponding RTP ports 10000-20000 are open on the server, and the IPs listed on this page https://www.twilio.com/docs/sip-trunking/ip-addresses can access the server. I made a call through Skype, and the error code displayed in the backend is 32011. In this situation, where is the most likely place where the issue could be occurring?

**Comment by tricksterANDthug** [comment]
I have also started the LiveKit server and the corresponding AI agent, the result is show below:
<img width="1333" alt="截屏2024-09-10 17 25 29" src="https://github.com/user-attachments/assets/3d3eff81-05df-42dd-8af8-f690e37a85ee">

**Comment by dennwc** [comment]
First, you may have noticed that LiveKit logs show a conflict error for SIP Trunks. Without proper configuration LiveKit SIP may reject the calls.

Second, I would suggest checking Twilio Error Logs to see what kind of error is reported there for this call. Downloading PCAP to diagnose these issues may be helpful as well.

Also, the screenshots do not show any logs for SIP service during the call. This may mean that the service is not getting any SIP messages at all. Could be a firewall or MTU issue.

**Comment by tricksterANDthug** [comment]
I want to ask, I have started the LiveKit-SIP service on an AWS EC2 server. What protocol should be configured in the AWS security group rules? Should it be HTTP, UDP, or TCP?

**Comment by larebksyed** [comment]
@tricksterANDthug How did you fix this issue? I am facing he same issue on livekit cloud.
