### ISSUE TITLE
livekit/sip docker image not found

### ISSUE THREAD

**Issue by Hollymingyi** [livekit/sip#22]
dear author,
   when i pull livekit/sip, it notice that there have no image named livekit/sip.   and when i try to build source code use mage command ,it notice me that :
    /root/go/pkg/mod/gopkg.in/hraban/opus.v2@v2.0.0-20230925203106-0188a62cb302/encoder.go:31: undefined reference to `OPUS_GET_IN_DTX',
  could u help me solve this problem?

**Comment by dennwc** [comment]
We are currently rolling out SIP integration for testing on LiveKit Cloud, so the Docker image will be up soon enough.

As for the second issue, it could be that `libopus-dev` on your system is older than the version required by `hraban/opus` library we use. The one installed on my machine reports version 1.3.1, for example. Can you check the version you have installed?

**Comment by Sean-Der** [comment]
Glad to hear that worked @Hollymingyi!

If anything else comes happy to help :)
