### ISSUE TITLE
Rejecting inbound flood

### ISSUE THREAD

**Issue by RanaGulraiz06** [livekit/sip#227]
I have set up the self-hosted live kit server and sip, but getting the following issue, when making inbound call:

```
2024-11-15T20:06:17.004Z    INFO    sip    sip/inbound.go:141    processing invite    {"nodeID": "NE_FAEJppF4wzxD", "callID": "SCL_MSsYCFd23tj8", "fromIP": "54.172.60.3", "toIP": "35.90.142.40:5060", "fromHost": "pitbchatbot.pstn.twilio.com", "fromUser": "hello", "toHost": "35.90.142.40", "toUser": "+18647547219", "sipTag": "91572002_c3356d0b_d5288544-bbc4-48b4-88d3-42f98ce47fb6", "twilioAccSID": "ACb4c6f583183c966930dd48dbb879ea1f", "twilioCallSID": "CA4298a31bf25878ce824c9b0da04c2bf2"}
2024-11-15T20:06:17.006Z    DEBUG    sip    sip/inbound.go:347    Rejecting inbound flood    {"nodeID": "NE_FAEJppF4wzxD", "callID": "SCL_MSsYCFd23tj8", "fromIP": "54.172.60.3", "toIP": "35.90.142.40:5060", "fromHost": "pitbchatbot.pstn.twilio.com", "fromUser": "hello", "toHost": "35.90.142.40", "toUser": "+18647547219", "sipTag": "91572002_c3356d0b_d5288544-bbc4-48b4-88d3-42f98ce47fb6", "twilioAccSID": "ACb4c6f583183c966930dd48dbb879ea1f", "twilioCallSID": "CA4298a31bf25878ce824c9b0da04c2bf2"}
```

**Comment by dennwc** [comment]
The server will consider all calls that match no [Inbound Trunks](https://docs.livekit.io/sip/trunk-inbound/) and [Dispatch Rules](https://docs.livekit.io/sip/dispatch-rule/) as spam and will reject them. Please make sure you configured these correctly. Our [quickstart guide](https://docs.livekit.io/sip/quickstarts/configuring-sip-trunk/) is a good place to start.

**Comment by raihan0824** [comment]
same problem here, have followed all the guide correctly but keep getting the same error

**Comment by raihan0824** [comment]
how do you fix it? @RanaGulraiz06

**Comment by dennwc** [comment]
@raihan0824 for self-hosted server, you could check LiveKit Server logs (not SIP), it should explain why specific call was rejected. But the reason is definitely some misconfiguration of inbound trunks and/or dispatch rules.

**Comment by raihan0824** [comment]
> [@raihan0824](https://github.com/raihan0824) for self-hosted server, you could check LiveKit Server logs (not SIP), it should explain why specific call was rejected. But the reason is definitely some misconfiguration of inbound trunks and/or dispatch rules.

when i made the call, the logs are shown on sip server but not on livekit server. i followed the inbound trunks and dispatch rules just like the guide. not sure what's going on here

**Comment by dennwc** [comment]
What the SIP logs show then?

It might be that LiveKit Server and LiveKit SIP cannot communicate with each other. Did you set the same Redis instance for both?

**Comment by raihan0824** [comment]
> What the SIP logs show then?
> 
> It might be that LiveKit Server and LiveKit SIP cannot communicate with each other. Did you set the same Redis instance for both?

yeah same redis. the sip logs are basically like this:

processing invite -> Rejecting inbound flood -> Closing inbound call

**Comment by raihan0824** [comment]
this is the sip logs:

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/ea89d988-daa1-48e7-af86-cdca3d1dba3e" />

**Comment by raihan0824** [comment]
this is the sip logs:

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/5a893262-80a3-407a-9072-0dba181ff73b" />

**Comment by dennwc** [comment]
OK we definitely need LiveKit Server logs to resolve this. Can you try enabling debug mode on it (in the config)?

```
logging:
    level: debug
```

**Comment by raihan0824** [comment]
> logging:
>     level: debug

i did this but it didnt change anything. still nothing show up on the livekit server logs

**Comment by raihan0824** [comment]
<img width="712" alt="Image" src="https://github.com/user-attachments/assets/de036914-82d9-4668-a346-aefdb0868bf8" />

all the servers are running well except when i made the call, livekit server wont show anything and "flood" is shown on the sip server log

**Comment by raihan0824** [comment]
should i reset the registered dispatch? if so, how to do that?

**Comment by raihan0824** [comment]
i suspect this is the problem with connecting the sip server and livekit server. Do you know how to solve this? below is my sip server config:

```
services:
  sip:
    image: livekit/sip
    network_mode: host
    environment:
      SIP_CONFIG_BODY: |
        api_key: '<API_KEY>'
        api_secret: '<API_SECRET>'
        ws_url: 'ws://localhost:7880'
        redis:
          address: 'localhost:6379'
        sip_port: 5060
        rtp_port: 10000-20000
        use_external_ip: true
        logging:
          level: debug
```

It's connected to the redis server but i don't know how to check if it's connected to my livekit server

**Comment by raihan0824** [comment]
when i tried to use the outbound call, this log appear on the livekit servet:

`2025-01-28T15:29:55.783Z	INFO	livekit.api	service/twirp.go:124	API AgentDispatchService.CreateDispatch	{"service": "AgentDispatchService", "method": "CreateDispatch", "duration": "167.685µs", "status": "500", "error": "could not find object", "code": "internal"}
`

I guess because it cannot find the sip server

**Comment by dennwc** [comment]
@raihan0824 could you please join our Slack instead? There might be some issues with the Agent code, etc. It's easier to discuss it on Slack.

**Comment by pathikb** [comment]
@raihan0824 were you able to solve this? I am getting the same error currently.

**Comment by flax3lbs** [comment]
I could create a new issue, but I'll add onto this one as there is currently no solution I can find.

I have a box where I'm running livekit and the sip gateway. Normally, there's an Asterisk instance running, so it receives calls. Asterisk is currently not running when I'm running these tests.

In the sip logs I get: (all the phone number replaced to protect the innocent)

`2025-08-28T19:31:39.720Z	INFO	sip	sip/inbound.go:178	processing invite	{"nodeID": "NE_Z4Epj6KkWpov", "callID": "SCL_eUkSnZ76Wig9", "fromIP": "10.35.217.6", "toIP": "10.31.170.151:5060", "fromHost": "10.35.217.6", "fromUser": "+15555559544", "toHost": "10.31.170.151", "toUser": "+15555553319", "sipTag": "gK08159011", "sipCallID": "55092406_32948756@10.35.217.6"}
2025-08-28T19:31:39.742Z	DEBUG	sip	sip/inbound.go:434	Rejecting inbound flood	{"nodeID": "NE_Z4Epj6KkWpov", "callID": "SCL_eUkSnZ76Wig9", "fromIP": "10.35.217.6", "toIP": "10.31.170.151:5060", "fromHost": "10.35.217.6", "fromUser": "+15555559544", "toHost": "10.31.170.151", "toUser": "+15555553319", "sipTag": "gK08159011", "sipCallID": "55092406_32948756@10.35.217.6", "sipTrunk": "ST_MnPa9gpMfnue", "jitterBuf": false, "sipTrunk": "ST_MnPa9gpMfnue"}
2025-08-28T19:31:39.742Z	DEBUG	Server transaction terminating	{"nodeID": "NE_Z4Epj6KkWpov", "caller": "transaction.Layer"}
2025-08-28T19:31:39.742Z	DEBUG	Server transaction destroyed	{"nodeID": "NE_Z4Epj6KkWpov", "caller": "transaction.Layer", "tx": "z9hG4bK08B82efdc007fb84acd__10.35.217.6__5060__INVITE"}
2025-08-28T19:31:39.743Z	INFO	sip	sip/inbound.go:782	Closing inbound call	{"nodeID": "NE_Z4Epj6KkWpov", "callID": "SCL_eUkSnZ76Wig9", "fromIP": "10.35.217.6", "toIP": "10.31.170.151:5060", "fromHost": "10.35.217.6", "fromUser": "+15555559544", "toHost": "10.31.170.151", "toUser": "+15555553319", "sipTag": "gK08159011", "sipCallID": "55092406_32948756@10.35.217.6", "sipTrunk": "ST_MnPa9gpMfnue", "jitterBuf": false, "sipTrunk": "ST_MnPa9gpMfnue", "status": 486, "reason": "flood"}`

In the livekit logs I get: 

`2025-08-28T19:31:39.732Z	DEBUG	livekit	service/ioservice_sip.go:151	SIP trunk matched for auth	{"toUser": "+15555553319", "fromUser": "+15555559544", "src": "10.35.217.6", "sipTrunk": "ST_MnPa9gpMfnue"}
2025-08-28T19:31:39.738Z	DEBUG	livekit	service/ioservice_sip.go:107	SIP trunk matched	{"toUser": "+15555553319", "fromUser": "+15555559544", "src": "10.35.217.6", "sipTrunk": "ST_MnPa9gpMfnue"}`

So the looking at the source code the "Rejecting inbound flood" appears to be an auth issue, but I'm not using auth ... at least I don't think I am.

From inbound.go:

`var pinPrompt bool
	switch disp.Result {
	default:
		err := fmt.Errorf("unexpected dispatch result: %v", disp.Result)
		c.log.Errorw("Rejecting inbound call", err)
		c.cc.RespondAndDrop(sip.StatusNotImplemented, "")
		c.close(true, callDropped, "unexpected-result")
		return psrpc.NewError(psrpc.Unimplemented, err)
	case DispatchNoRuleDrop:
		c.log.Debugw("Rejecting inbound flood")
		c.cc.Drop()
		c.close(false, callFlood, "flood")
		return psrpc.NewErrorf(psrpc.PermissionDenied, "call was not authorized by trunk configuration")
	case DispatchNoRuleReject:
		c.log.Infow("Rejecting inbound call, doesn't match any Dispatch Rules")
		c.cc.RespondAndDrop(sip.StatusNotFound, "Does not match Trunks or Dispatch Rules")
		c.close(false, callDropped, "no-dispatch")
		return psrpc.NewErrorf(psrpc.NotFound, "no trunk configuration for call")
	case DispatchAccept:
		pinPrompt = false
	case DispatchRequestPin:
		pinPrompt = true
	}`

Below are the trunk config and dispatch rule, queried by livekit-cli:

`Using api-key, api-secret from environment
┌─────────────────┬──────────────────┬──────────────┬──────────────────┬────────────────┬────────────────┬────────────┬─────────┬──────────┐
│ SipTrunkID      │ Name             │ Numbers      │ AllowedAddresses │ AllowedNumbers │ Authentication │ Encryption │ Headers │ Metadata │
├─────────────────┼──────────────────┼──────────────┼──────────────────┼────────────────┼────────────────┼────────────┼─────────┼──────────┤
│ ST_RvwB7PyxZhX7 │ Asterisk Inbound │ +15555553319 │ 10.35.217.6/32   │                │                │ DISABLE    │         │          │
└─────────────────┴──────────────────┴──────────────┴──────────────────┴────────────────┴────────────────┴────────────┴─────────┴──────────┘`

`Using api-key, api-secret from environment
┌───────────────────┬──────────────────────┬──────────────────┬────────┬──────────────┬─────┬────────────┬────────────┐
│ SipDispatchRuleID │ Name                 │ SipTrunks        │ Type   │ RoomName     │ Pin │ Attributes │ Agents     │
├───────────────────┼──────────────────────┼──────────────────┼────────┼──────────────┼─────┼────────────┼────────────┤
│ SDR_qw4ethwH7jj2  │ Support Inbound Rule │ Asterisk Inbound │ Direct │ support_room │     │ map[]      │ support-ai │
└───────────────────┴──────────────────────┴──────────────────┴────────┴──────────────┴─────┴────────────┴────────────┘`

I have an AI agent listening in the support_room awaiting the call. Any help would be much appreciated.
