### ISSUE TITLE
create sip trunk

### ISSUE THREAD

**Issue by Hollymingyi** [livekit/sip#23]
dear author,
   when i use go sdk to create sip trunk ,it return error like below:
    "error": "twirp error bad_route: Error from intermediary with HTTP status code 404 \"Not Found\""

 the func is sipClient().CreateSIPTrunk
 the params are:
     inboundAddresses := []string{"10.2.14.199"}
     outboundAddress := "10.2.14.199"
     outboundNumber := "12345"
     inboundNumbersRegex := []string{"12345"}

the livekit version is v1.5.1 and go sdk version is v1.1.4,what should i do?

**Comment by Sean-Der** [comment]
Hi @Hollymingyi 

Full SIP Support isn't available in a tagged version yet. Would you mind building a LiveKit instance @ `dfcafff955d6b51796d0611192e57e5f83fccde7`

We will tag a new version very soon! When we do I will resolve the issue.

**Comment by Hollymingyi** [comment]
ok,i will have a try,thank u!

**Comment by Hollymingyi** [comment]
hi sean,
  after i tried called into livekit room via sipendpoint ,it works.but only audio ,no video ,could u tell where i should config to solve them ?

**Comment by Hollymingyi** [comment]
hi sean,
     when livekit answer , return 200 message , the sdp message have m=audio  only ,have no m=video tag.
   
<img width="576" alt="无标题" src="https://github.com/livekit/sip/assets/32379566/c4733278-8db8-4ecb-a74d-9a6183bd2f95">

**Comment by dennwc** [comment]
We do not plan to support video stream negotiation over SIP currently.
