### ISSUE TITLE
livekit sip with freepbx

### ISSUE THREAD

**Issue by BisarAhmed** [livekit/sip#233]
i read all the documentation but could gather enough knowledge to config livekit with freepbx, i will be thanks full for any explanation and guidance 

@ftsef in your issue [Livekit-SIP with Asterisk](https://github.com/livekit/sip/issues/112) looks like you integrated the livekit with asterisk. please could provide it.

**Comment by blobgetblob** [comment]
any updates on this? or @BisarAhmed did you found way to configure the freepbx
