### ISSUE TITLE
SIP INVITE dropped by LiveKit due to P-Charging-Vector header

### ISSUE THREAD

**Issue by robertvy** [livekit/sip#251]
## Description  
We observed an issue where SIP INVITE requests containing the `P-Charging-Vector` header were not processed by LiveKit. This header is typically added by some carriers for billing purposes and is being passed to LiveKit without modification.  

While FreeSWITCH and Asterisk accept and process this header without issue, LiveKit appears to ignore/drop the INVITE entirely, resulting in dropped calls.  

## Steps to Reproduce  
1. Place a call routed through a carrier that uses P-Charging Vector
2. Confirm the `P-Charging-Vector` header is present in the SIP INVITE.  
3. Check if LiveKit fails to respond to the INVITE or drops the call.

## Expected Behavior  
LiveKit should either:  
- Handle the `P-Charging-Vector` header appropriately, or  
- Respond with an error message indicating unsupported headers.

## Observed Behavior  
LiveKit fails to process the SIP INVITE and does not respond, leading to dropped calls.

## Notes  
- The `P-Charging-Vector` header is standard in some SIP implementations but may not be universally supported.  
- FreeSWITCH handles the header correctly, but LiveKit seems to require addition

## References  
- [P-Charging-Vector Documentation (Ribbon)](https://publicdoc.rbbn.com/display/SBXDOC92/P-Charging-Vector+Header)  
- [P-Charging-Vector Documentation (AudioCodes)](https://techdocs.audiocodes.com/session-border-controller-sbc/sip-manipulation/version-740/Content/SIPManipulation/P%20Charging%20Vector.htm?TocPath=Message%20Manipulation%20Syntax%20Reference%7CHeader%20Types%7C_____15)  

## Additional Information  
This issue might require LiveKit to update its SIP handling logic to support headers like `P-Charging-Vector` or provide a configurable way to strip or handle such headers.

**Comment by robertvy** [comment]
![Uploading sngrep2.png…]()

**Comment by robertvy** [comment]
<img width="1648" alt="SCR-20241226-oamc" src="https://github.com/user-attachments/assets/2894ea6c-f745-48c5-ad29-429e3b8be292" />

**Comment by dennwc** [comment]
Thank you for a detailed description!

Do you have further details about an error you are seeing with `P-Charging-Vector` header? Why are you specifically considering that header to be an issue?

**Comment by robertvy** [comment]
hey @dennwc after we removed the header for the call-leg with livekit the calls went through without issues. We do not have any feedback from Livekit as the cloud version does not provide us with SIP server logs. What I can tell you is that the invites receive no response and also no room gets created in Livekit.

This was the fix for us:
<img width="458" alt="SCR-20241226-otlf" src="https://github.com/user-attachments/assets/10ac228d-7e22-439b-8d7c-e1237da42c5e" />

**Comment by dennwc** [comment]
Looks like we confirmed that it was caused by UDP packets larger than network path MTU. Suggested switching to TCP protocol for the inbound calls.

**Comment by robertvy** [comment]
yes, that's correct. Switching to TCP resolved the issue.
