### ISSUE TITLE
how to make call out

### ISSUE THREAD

**Issue by Hollymingyi** [livekit/sip#26]
hi author,
   could u tell me how to make outbound call ?

**Comment by boks1971** [comment]
Please see - https://docs.livekit.io/sip/#outbound-sip

**Comment by dennwc** [comment]
Right, we need to add a proper section for adding SIP Participants, similar to how we describe SIP Trunks.

You'll need to make a JSON file (`sipParticipant.json`) with the following structure:

```json
{
	"sipTrunkId": "<your trunk ID>",
	"sipCallTo": "+123456789",
	"roomName": "some-room",
	"participantIdentity": "Test Call"
}
```

And then, with SIP server running, add the participant via:

```bash
export LIVEKIT_URL=https://my-livekit-host
export LIVEKIT_API_KEY=livekit-api-key
export LIVEKIT_API_SECRET=livekit-api-secret
livekit-cli create-sip-participant --request sipParticipant.json
```

Also, make sure that SIP is at least at commit ec274a008f458df2c420a0dac21ff9cca6e4697c.

Please let me know if it works. Outbound still have a few minor issues that I want to address.

**Comment by Hollymingyi** [comment]
hi dennwc,
   ok ,i will have a try., and  i will try to mix video from lk and push into sip server,  maybe u can give me some advice ,thank you so much.

**Comment by dennwc** [comment]
Docs were updated for outbound, so closing this one.

https://docs.livekit.io/sip/sip-participant/
