### ISSUE TITLE
which profile should i use for video call

### ISSUE THREAD

**Issue by Hollymingyi** [livekit/sip#34]
hi author,
   when i answered video call with sdp :
a=rtpmap:102 H264/90000
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
the video image which send into livekit/sip is very fuzzy, i just dont know how to get rid of it .could u help me to give me some advice?

**Comment by davidzhao** [comment]
See: https://github.com/livekit/sip/issues/24
