### ISSUE TITLE
demo of inboud rule 

### ISSUE THREAD

**Issue by Hollymingyi** [livekit/sip#39]
hi author，
   i added direct rule and bind trunk ，sometimes the route it worked ，but sometimes it cannot work well.could u give some real demo about create trunk and rule(direct) ,thank u

**Comment by dennwc** [comment]
You are right, we need better examples :+1: 

Could you please send logs from the SIP bridge when it fails?

In the meantime, is example in https://github.com/livekit/sip/issues/38 helpful?

**Comment by dennwc** [comment]
Docs were updated, so closing: https://docs.livekit.io/sip/
