### ISSUE TITLE
Codec negotiation issue

### ISSUE THREAD

**Issue by denyspozniak** [livekit/sip#95]
Hello!

As far as I can see, there is a problem in the choice of codecs.
My test scenario is like this:
sip uac (phonerlite) -> sip uas (livekit sip gw)

sip-uac SIP INVITE SDP:

```
v=0
o=- 3094585973 1 IN IP4 10.1.15.11
s=PhonerLite/3.24
c=IN IP4 10.1.15.11
t=0 0
m=audio 42236 RTP/AVP 8 0 3 9 18 101
a=ssrc:1406527973
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:3 GSM/8000
a=rtpmap:9 G722/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=yes
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=rtcp:42237
```

sip-uas (200 OK/SDP):
```
v=0
o=- 3094585973 3094585975 IN IP4 10.1.130.32
s=LiveKit
c=IN IP4 10.1.130.32
t=0 0
m=audio 10013 RTP/AVP 0 101
a=rtpmap:9 G722/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:150
a=sendrecv
````

It is clear from reply that the livekit agrees to work on PCMU (payload 0) with dtmf RFC2833 (m=audio 10013 RTP/AVP 0 101), although for some reason it sends a rtpmap for G722 (a=rtpmap:9 G722/8000).
Well, besides that, the RTP stream itself also comes from livekit via G722

**Comment by dennwc** [comment]
Clearly a bug. I disabled G722 specifically because there was in issue with negotiation, but didn't have time to check why.

**Comment by dennwc** [comment]
@denyspozniak I pushed a fix, feel free to reopen if there are any other issues here.
